# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  #  Configure base
  config.vm.define "linux" do |linux|
      linux.vm.box = 'centos/7'
      linux.ssh.forward_agent = true
      linux.ssh.insert_key = true
      linux.vm.hostname = "linux.vm"
      linux.vm.network :private_network, :ip => "192.168.77.10"
      linux.vm.provision :hosts, :sync_hosts => true

      linux.vm.provision "shell", inline: <<-SHELL
           sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config    
           service sshd restart
      SHELL
   end

end
